// apps/solid-start-todo/src/components/todo/todo-table.tsx
import { createQuery } from "@tanstack/solid-query";
import { For, Match, Switch } from "solid-js";

import { AddTodoModal } from "~/components/todo/add-todo-modal";
import { DeleteDatabase } from "~/components/todo/delete-database";
import { DeleteTodo } from "~/components/todo/delete-todo";
import { EditTodo } from "~/components/todo/edit-todo";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "~/components/ui/table";
import { getTodosOptions } from "~/data/todo-db";

export const TodoTable = () => {
  const query = createQuery(getTodosOptions);

  return (
    <>
      <div class="flex w-full justify-end">
        <AddTodoModal />
      </div>
      <div>
        <h1 class="mb-2 text-xl font-bold">
          Todos
        </h1>
        <Switch>
          <Match when={query.isPending}>
            <p>
              Loading...
            </p>
          </Match>
          <Match when={query.isSuccess}>

            <Table class="mx-auto max-w-3xl border-2">
              <TableHeader>
                <TableRow>
                  <TableHead>
                    Name
                  </TableHead>
                  <TableHead>
                    Actions
                  </TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <For each={query.data}>
                  {(todo) => {
                    return (
                      <TableRow>
                        <TableCell class="text-left">
                          {todo.name}
                        </TableCell>
                        <TableCell>
                          <div class="flex items-center justify-end gap-1">
                            <EditTodo todo={todo} />
                            <DeleteTodo todo={todo} />
                          </div>
                        </TableCell>
                      </TableRow>
                    );
                  }}
                </For>
              </TableBody>
            </Table>
          </Match>
        </Switch>
      </div>
      <DeleteDatabase />
    </>
  );
};

// apps/tanstack-router-todo/src/components/todo/todo-table.tsx
import { Button } from "@nextui-org/button";
import { getKeyValue, Table, TableBody, TableCell, TableColumn, TableHeader, TableRow } from "@nextui-org/table";
import { useQuery } from "@tanstack/react-query";
import { PencilIcon } from "lucide-react";

import { getTodosOptions } from "../../data/todo-database";
import { AddTodo } from "./add-todo";
import { DeleteTodo } from "./delete-todo";

const columns = [
  {
    key: "name",
    label: "Name",
  },
  {
    key: "actions",
    label: "Actions",
  },
];

export const TodoTable = () => {
  const { data, isPending } = useQuery(getTodosOptions());

  return (
    <>
      <div>
        <AddTodo />
      </div>
      <div >
        <h1 className="mb-2 text-xl font-bold">
          Todos
        </h1>
        {isPending &&
          <p>
            Loading...
          </p>}
        {data && (
          <Table
            isHeaderSticky
            isStriped
            aria-label="Todos"
            className="mx-auto max-w-3xl"
          >
            <TableHeader columns={columns}>
              {(column) => {
                return (
                  <TableColumn key={column.key}>
                    {column.label}
                  </TableColumn>
                );
              }}
            </TableHeader>
            <TableBody items={data}>
              {(item) => {
                return (
                  <TableRow key={item.id}>
                    {(columnKey) => {
                      if ("actions" === columnKey) {
                        return (
                          <TableCell >
                            <div className="flex gap-1">
                              <Button
                                isIconOnly
                                className="border-0"
                                variant="ghost"
                              >
                                <PencilIcon className="size-4" />
                              </Button>
                              <DeleteTodo todo={item} />
                            </div>
                          </TableCell>
                        );
                      }

                      return (
                        <TableCell>
                          {getKeyValue(item, columnKey)}
                        </TableCell>
                      );
                    }}
                  </TableRow>
                );
              }}
            </TableBody>
          </Table>
        )}
      </div>
    </>
  );
};
