// apps/tanstack-router-todo/src/components/todo/delete-todo.tsx
import { Button } from "@nextui-org/button";
import { Modal, ModalBody, ModalContent, ModalFooter, ModalHeader, useDisclosure } from "@nextui-org/modal";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { TrashIcon } from "lucide-react";

import { deleteTodoOptions, getTodosOptions, type Todo } from "../../data/todo-database";

type DeleteTodoProperties = {
  todo: Todo;
};

export const DeleteTodo = ({ todo }: Readonly<DeleteTodoProperties>) => {
  const queryClient = useQueryClient();
  const {
    isOpen, onClose: handleClose, onOpen, onOpenChange,
  } = useDisclosure();

  const { isPending, mutate } = useMutation({
    ...deleteTodoOptions(),
    onSettled: async () => {
      await queryClient.invalidateQueries(getTodosOptions()).finally(() => {
        handleClose();
      });
    },
  });

  return (
    <>
      <Button
        isIconOnly
        className="border-0"
        onPress={onOpen}
        variant="ghost"
      >
        <TrashIcon className="size-4 text-danger" />
      </Button>
      <Modal
        isOpen={isOpen}
        onOpenChange={onOpenChange}
      >
        <ModalContent>
          {(onClose) => {
            return (
              <>
                <ModalHeader>
                  Delete Todo
                  {todo.name}
                  ?
                </ModalHeader>
                <ModalBody>
                  Are you sure you want to delete this?
                </ModalBody>
                <ModalFooter>
                  <Button
                    color="primary"
                    onPress={onClose}
                  >
                    Close
                  </Button>
                  <Button
                    onPress={() => {
                      mutate(todo.id);
                    }}
                    color="danger"
                    isLoading={isPending}
                    type="submit"
                  >
                    Delete
                  </Button>
                </ModalFooter>
              </>
            );
          }}
        </ModalContent>
      </Modal>
    </>
  );
};

// apps/solid-start-todo/src/components/todo/delete-todo.tsx
import { createMutation, useQueryClient } from "@tanstack/solid-query";
import { TrashIcon } from "lucide-solid";
import { createSignal } from "solid-js";

import { Button } from "~/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription, DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "~/components/ui/dialog";
import { deleteTodoOptions, getTodosOptions, type Todo } from "~/data/todo-database";
import { logError } from "~/utils/console";

export const DeleteTodo = (properties: { todo: Todo }) => {
  const [isOpen, setIsOpen] = createSignal(false);
  const queryClient = useQueryClient();

  const mutation = createMutation(() => {
    return {
      ...deleteTodoOptions(properties.todo.id),
      onSettled() {
        queryClient
          .invalidateQueries({ queryKey: getTodosOptions().queryKey })
          .catch(logError)
          .finally(() => {
            setIsOpen(false);
          });
      },
    };
  });

  return (
    <Dialog
      onOpenChange={setIsOpen}
      open={isOpen()}
    >
      <DialogTrigger
        as={Button}
        variant="ghost"
      >
        <TrashIcon class="size-4 text-destructive" />
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>
            Delete Todo
            {" "}
            {properties.todo.name}
            ?
          </DialogTitle>
          <DialogDescription>
            Are you sure you want to delete this?
          </DialogDescription>
        </DialogHeader>
        <DialogFooter>
          <Button
            onClick={() => {
              mutation.mutate();
            }}
            variant="destructive"
          >
            Delete
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
